[package]
name = "spaday-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
pnet = "0.35.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
